/* Generated by Yosys 0.20+42 (git sha1 1c36f4cc2, clang 14.0.0-1ubuntu1 -fPIC -Os) */

module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(count[0]),
    .B(rst),
    .Y(_00_)
  );
  sky130_fd_sc_hd__o21bai_1 _09_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1_N(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _10_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _11_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _12_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor3_1 _13_ (
    .A(rst),
    .B(_05_),
    .C(_06_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a41oi_1 _14_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[2]),
    .A4(count[3]),
    .B1(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21a_1 _15_ (
    .A1(count[3]),
    .A2(_05_),
    .B1(_07_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule
